spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rpa_dev;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/migration/V1__init.sql

jwt:
  secret: dev-secret-dev-secret-dev-secret-dev-secret
  expiration: 86400000
